### PR TITLE
Final Release APK Added

### PR DESCRIPTION
**Pull request by abs51295**
Added APK for final release.

### CODE REVIEW

**Comment by abs51295** [comment]
@MeepyMay Please review 😄

**Comment by vaibhavsingh97** [comment]
@abs51295 app is not installing on marshmallow
Device Name: LeEco Le2
Android version: 6.0.1

**Comment by abs51295** [comment]
@vaibhavsingh97 Can you post error log?

**Comment by vaibhavsingh97** [comment]
@abs51295 Sorry! My bad...i haven't uninstalled the previous version of app. BUt the app is buttery smooth and functionality is working as expected. :tada: :tada:

**Pull request merged**
