### PR TITLE
Minor UI issue fix

### LINKED ISSUE #27: Minor UI Issues
Fix the following 

- Width of Fb Sign-In and Google Sign-in button differs at runtime.
- The text displayed on Fb Sign-In is "Continue with Facebook", should be changed to "Sign-In with Facebook"

### PR DESCRIPTION
**Pull request by vaibhavsingh97**
fixes #27 
Actual Behaviour:
screenshot_20170731-152059

Screenshot after fix:
screenshot_20170731-151856

### CODE REVIEW

**Comment by vaibhavsingh97** [comment]
@chhavip Please review

**Comment by abs51295** [comment]
@vaibhavsingh97 @chhavip I and @MeepyMay had a meeting and decided to change UI using the Firebase UI [library](https://github.com/firebase/FirebaseUI-Android/blob/master/auth/README.md). And also we are adding multiple logins including Twitter, Google and Facebook and possibly others in future. So I think it's best to pause this PR as of now since I only can access the Firebase account and also this UI change would need @MeepyMay 's approval (since it's major change)  so it's best that I handle it. Thank you @vaibhavsingh97 for your contribution.

**Comment by abs51295** [comment]
@MeepyMay PR #50 solves the problem. I think this PR can be closed now.

**Comment by MeepyMay** [comment]
Closed. Thank you @abs51295

**Comment by abs51295** [comment]
@m-murad please close this.

**Pull request closed without merging**
