### PR TITLE
Revert "Speaker Details Page"

### PR DESCRIPTION
**Pull request by chhavip**
Reverts systers/conference-android#39 as ETouches are not being used anymore.

### CODE REVIEW

**Comment by chhavip** [comment]
@MeepyMay This PR needs to be merged in order to revert changes made for ETouches.

**Comment by chhavip** [comment]
@abs51295 for this PR to be reverted there are pending conflicts, can you take a look?

**Comment by abs51295** [comment]
I cannot see a resolve conflicts button @chhavip and I don't know which branch to update for this. I think since you created PR you can see the resolve conflicts button.

**Comment by chhavip** [comment]
@abs51295 Why does this PR have merge conflicts? Even I do not have a resolve conflicts option visible but there are conflicts visible. If needed this PR can be closed and you can revert the original speaker details PR without conflicts

**Comment by abs51295** [comment]
@m-murad please close this.

**Pull request closed without merging**
